@Api_HostAddress = https://localhost:7273

### Shorten a URL (no custom alias)
POST {{Api_HostAddress}}/urlshortener/shorten
Content-Type: application/json

{
  "fullUrl": "https://example.com/very/long/url"
}

###

### Shorten a URL (with custom alias)
POST {{Api_HostAddress}}/urlshortener/shorten
Content-Type: application/json

{
  "fullUrl": "https://example.com/very/long/url",
  "customAlias": "my-custom-alias"
}

###

### Redirect to full URL
GET {{Api_HostAddress}}/urlshortener/my-custom-alias

###

### Delete a shortened URL
DELETE {{Api_HostAddress}}/urlshortener/my-custom-alias

###

### List all shortened URLs
GET {{Api_HostAddress}}/urlshortener/urls
Accept: application/json

###
